/**
 * Gradient tiles for the restaurant-category strip (see RestaurantCategoryGrid.tsx) — product
 * images themselves are real local files now (frontend/public/images/products/…, generated by
 * scripts/generate-placeholder-images.mjs), rendered via next/image, not these CSS gradients.
 * Class strings must stay as literal, complete strings (not built via template interpolation)
 * so Tailwind's content scan can find them — see tailwind.config.ts content globs, which
 * include this file.
 */
export const RESTAURANT_CATEGORY_GRADIENTS: Record<string, string> = {
  pizzeria: "bg-gradient-to-br from-[#c2410c] to-[#ea580c]",
  "fast-food": "bg-gradient-to-br from-[#b45309] to-[#f59e0b]",
  "bar-cafe": "bg-gradient-to-br from-[#3f2d23] to-[#6f4e37]",
  snack: "bg-gradient-to-br from-[#854d0e] to-[#ca8a04]",
  collectivite: "bg-gradient-to-br from-[#1e293b] to-[#475569]",
  boucherie: "bg-gradient-to-br from-[#500724] to-[#9f1239]",
  patisserie: "bg-gradient-to-br from-[#9d174d] to-[#ec4899]",
  "hotel-chaine": "bg-gradient-to-br from-[#18181b] to-[#3f3f46]",
};

const DEFAULT_GRADIENT = "bg-gradient-to-br from-primary to-primary/70";

export function getRestaurantCategoryGradient(slug: string) {
  return RESTAURANT_CATEGORY_GRADIENTS[slug] ?? DEFAULT_GRADIENT;
}
